[behaviors.h, behaviors.cpp, cell.h] Behaviors added
LeoProko/huy_simulation pull request #13
Opened 2021-07-28 14:51 UTC by levelup0

2021-07-28 16:02 UTC, LeoProko requested changes

2021-07-28 16:17 UTC, LeoProko requested changes

2021-07-28 16:17 UTC, LeoProko commented on map/include/cell.h
> +class Cell {
забыли добавить очередь из ботов

2021-07-28 19:08 UTC, levelup0 commented on map/include/cell.h
> +class Cell {
В однопоточной версии наверное удобнее будет сделать вектор, а не очередь.

2021-07-28 19:10 UTC, levelup0 commented on map/include/cell.h
> +class Cell {
Даже не вектор, а сет, чтобы удобнее было удалять и искать двух ботов для размножения.

2021-07-29 10:03 UTC, LeoProko requested changes

2021-07-29 10:03 UTC, LeoProko commented on map/src/cell.cpp
> +#include "cell.h";
лишняя точка с запятой

2021-07-29 10:03 UTC, LeoProko commented on map/include/cell.h
> +    std::set<Bot> bots_;
кажется, здесь надо еще доопределить сет, чтобы в топе у нас были самые "attractive"

2021-07-29 10:04 UTC, LeoProko commented
Еще в симэйк листе мапы не подключается либа behaviors

2021-07-29 10:07 UTC, LeoProko commented on map/include/cell.h
> +    std::set<Bot> bots_;
И еще <set> не подключен

2021-07-29 10:16 UTC, levelup0 commented
А не будет проблемы из за того, что в behaviors подключается map, а в map - behaviors?

2021-07-29 10:22 UTC, LeoProko commented
> А не будет проблемы из за того, что в behaviors подключается map, а в map - behaviors?

будет, поэтому надо с этим как-то бороться. если не хочется придумывать какие-то дополнительные функции или возиться с симэйком, то можно cell и position вынести в отдельную папку

2021-07-29 10:24 UTC, levelup0 commented
можно наверное просто все функции написать в cell и не запариваться

2021-07-29 10:26 UTC, LeoProko commented
> можно наверное просто все функции написать в cell и не запариваться

нужен совзон, а то комментами на гитхабе сложновато продуктивно общаться)

2021-07-29 14:02 UTC, LeoProko approved these changes

2021-07-29 14:02 UTC, merged