Bot constructor and new genes added
LeoProko/huy_simulation pull request #14
Opened 2021-07-28 16:00 UTC by levelup0

2021-07-28 16:17 UTC, LeoProko requested changes

2021-07-28 16:17 UTC, LeoProko commented on bot/src/bot.cpp
> +    float coeff = 150./(militancy_ + intelligence_ + attractiveness_);
не хватает пробелов вокруг слэша

2021-07-28 16:17 UTC, LeoProko commented on bot/include/bot.h
> +    Bot(Bot& mother, Bot& father);
мы родителей не меняем, поэтому давай принимать их по константной ссылке

2021-07-28 16:17 UTC, LeoProko commented on bot/src/bot.cpp
> +    , health_(100)
мб здоровье тоже как-то наследовать? типа если родители хлипкие, то и ребенок должен быть такой же

2021-07-28 16:17 UTC, LeoProko commented on bot/src/bot.cpp
> +    , food_amount_(1)
надо походу делать больше одного, типа около 5-10 или как-то наследовать от родителей, потому что, кажется, что одной еды им не хватит для базового выживания

2021-07-28 16:17 UTC, LeoProko commented on bot/src/bot.cpp
> +    float coeff = 150./(militancy_ + intelligence_ + attractiveness_);
same

2021-07-28 19:31 UTC, levelup0 commented on bot/src/bot.cpp
> +    , health_(100)
мне кажется, что наследуются гены, они константные для каждого из существ на протяжении всей его жизни. а здоровье - это текущая характеристика, оно может меняться.

2021-07-28 19:34 UTC, LeoProko commented on bot/src/bot.cpp
> +    , health_(100)
просто как-то логичнее, что если два слабых существа ебутся, то у них рождается слабый ребенок, чтобы их род скорее вымер

2021-07-28 20:16 UTC, LeoProko requested changes

2021-07-28 20:16 UTC, LeoProko commented on bot/src/bot.cpp
> +    float coeff = 50. * genes_amount_ / (militancy_ + intelligence_ + attractiveness_ + childern_amount_ + children_health_);
`genes_amount_` и каждый из  `(militancy_ + intelligence_ + attractiveness_ + childern_amount_ + children_health_)` у нас `int`, поэтому при подсчете `coeff` от компилятора к компилятору может произойти непредсказуемость. Надо или кастануть их всех к флоату или все в интах считать

2021-07-28 20:16 UTC, LeoProko commented on bot/include/bot.h
> +    Bot(const Bot& mother, const Bot& father, int healt);
очепятка в health

2021-07-29 10:20 UTC, LeoProko commented on bot/src/bot.cpp
> +        *genes_iter_[i] = std::rand() % 101;
такой код работать не будет. у тебя вектор инициализируется нулптрами, а потом ты их же разыменовываешь. происходит обращение у нулевому указателю.
ты работаешь с этим вектором, как с вектором интов, поэтому может его таким и сделать?

2021-07-29 10:20 UTC, LeoProko commented on bot/include/bot.h
> +    std::vector<int*> genes_iter_;
надо это вывести на общее голосование. честно говоря, раньше было нагляднее

2021-07-29 13:46 UTC, LeoProko requested changes

2021-07-29 13:46 UTC, LeoProko commented on bot/include/bot.h
> +    void fill_genes_iter();
Эту функцию нужно будет вызвать в конструкторах бота

2021-07-29 16:08 UTC, LeoProko approved these changes

2021-07-29 16:13 UTC, merged