Write move function
LeoProko/huy_simulation pull request #18
Opened 2021-07-31 21:39 UTC by levelup0

2021-08-01 10:57 UTC, LeoProko requested changes

2021-08-01 10:57 UTC, LeoProko commented on bot/src/bot.cpp
> +    *genes_iter_[i] = std::rand() % 100;
кажется, это лишнее, потому что ты уже сделал то же самое в строках 17-22

2021-08-01 10:57 UTC, LeoProko commented on map/include/map.h
> +    void spawn_bots(std::deque<Bot>& all_bots, int bot_count);
в этом случает `bot_count` будет излишним, потому что эта инфа есть в `all_bots`

2021-08-01 10:57 UTC, LeoProko commented on map/include/map.h
>      void respawn_food();
`respawn_food` вызывается вроде только из `Map`, поэтому его лучше сделать приватным

2021-08-01 10:57 UTC, LeoProko commented on map/include/map.h
> +    Map(std::deque<Bot>& all_bots, int size, int bots_amount = 0, int food_amount = 0);
здесь тоже `bots_amount` можно убрать

2021-08-01 10:57 UTC, LeoProko commented on bot/include/bot.h
> +    int militancy_       = std::rand() % 100;
все ранды лучше заменть на [mersenne_twister_engine](https://en.cppreference.com/w/cpp/numeric/random/mersenne_twister_engine)
здесь рандом будет получше

2021-08-01 10:57 UTC, LeoProko commented on run/src/run.cpp
> +void Run::init(std::deque<Bot>& all_bots, int map_size, int bots_amount, int days_amount) {
здесь нужно еще добавить в `all_bots` `bots_amount` ботов

2021-08-01 10:57 UTC, LeoProko commented on run/src/run.cpp
> +  std::set<Position> used_positions;
это можно заменить на проход по ботам, потому что у тебя в ботах есть поле `position_`

2021-08-01 10:57 UTC, LeoProko commented on bot/src/bot.cpp
> +    *genes_iter_[i] = std::min(std::max(*genes_iter_[i], 0), 100);
здесь нужно 100 заменить на 99, потому что у нас гены от 0 до 99

2021-08-01 10:57 UTC, LeoProko commented on move/src/move.cpp
> +void move(Cell& cell, Map& map) {
move должен принимать бота и карту, потому что у нас проход по ботам, а не по карте

2021-08-01 10:57 UTC, LeoProko commented on move/src/move.cpp
> +void move(Cell& cell, Map& map) {
в Run ты как раз и передаешь бота и карту, но здесь почему-то ячейка и карта

2021-08-01 10:57 UTC, LeoProko commented on move/src/move.cpp
> +        Bot& bot = *cell.bots_.front();
зачем бота разыменовывать? это лишняя трата ресурсов

2021-08-01 12:08 UTC, levelup0 commented on map/include/map.h
> +    void spawn_bots(std::deque<Bot>& all_bots, int bot_count);
нет, наоборот, мы в all_bots кладем новых ботов. когда он туда передается, он пустой.

2021-08-01 12:13 UTC, levelup0 commented on move/src/move.cpp
> +        Bot& bot = *cell.bots_.front();
хз, удобнее везде писать bot, чем *cell.bots_.front() и нагляднее.

2021-08-01 12:14 UTC, levelup0 commented on run/src/run.cpp
> +void Run::init(std::deque<Bot>& all_bots, int map_size, int bots_amount, int days_amount) {
они по идее добавляются в spawn_bots, который вызывается в конструкторе Map

2021-08-01 12:29 UTC, LeoProko commented on move/src/move.cpp
> +        Bot& bot = *cell.bots_.front();
Да, но мув должен понимать бота, а не ячейку

2021-08-02 07:34 UTC, LeoProko requested changes

2021-08-02 07:34 UTC, LeoProko commented on bot/src/bot.cpp
> +    : position_(mother.position_.x, mother.position_.y),
запятую надо перенести под двоеточие

2021-08-02 07:34 UTC, LeoProko commented on map/src/map.cpp
> +        map_[rand() % size_][rand() % size_].bots_.push_back(&all_bots.back());
здесь происходит конфликт позиций в боте и в мапе.
обрати внимание на [конструктор бота от размера](https://github.com/LeoProko/huy_simulation/blob/write_move_function/bot/src/bot.cpp#L4)

поэтому 16 строку надо заменить на 
```cpp
map_[all_bots.back().position_].bots_.push_back(&all_bots.back());
```

2021-08-02 07:34 UTC, LeoProko commented on map/src/map.cpp
> +        map_[rand() % size_][rand() % size_].food_counter_ += std::rand() % 10;
кажется, здесь рушится логика `food_amount_`

2021-08-02 07:34 UTC, LeoProko commented on position/src/position.cpp
> +    return first.y < second.y;
давай воспользуемся модным способом и напишем 
```cpp
return std::tie(first.x, first.y) < std::tie(second.x, second.y)
```

для этого надо подключить `<tuple>`

2021-08-02 07:34 UTC, LeoProko commented on run/include/run.h
> +#include <set>
`<set>` и `<memory>` теперь нигде не используются, поэтому их надо удалить

2021-08-02 07:34 UTC, LeoProko commented on run/src/run.cpp
> +  std::deque<Bot> all_bots;
надо переделать на `std::list`, потому что нам нужно быстрое удаление из середины

2021-08-02 13:07 UTC, levelup0 commented on position/src/position.cpp
> +    return first.y < second.y;
На самом деле этот оператор, как и оператор ==, нам уже не нужны, я их просто удалю

2021-08-02 14:49 UTC, LeoProko approved these changes
Лев, вы проделали большую и очень выжную работу. Молодец!
Выпишем вам похвальную грамоту

2021-08-02 16:16 UTC, merged