cell reproduce and split_food
LeoProko/huy_simulation pull request #20
Opened 2021-08-02 13:39 UTC by neudachina

2021-08-02 14:13 UTC, levelup0 commented on cell/include/cell.h
> +    // total_health += (bot.militancy_ * 0.6 + bot.health_ * 0.4),
не очень понятно, откуда эта функция взялась честно говоря, к тому же, функция `split_food' вызывается для клетки и в ней в любом случае будет осуществляться проход по всем ботам, так что по времени работы программа не особо изменится. по какой формуле будет рассчитываться прибавка каждого бота к здоровью?

2021-08-02 14:17 UTC, levelup0 commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](Bot b1, Bot b2) { return b2 < b1; });
Вроде у нас уже есть оператор < для ботов, который сравнивает привлекательность, так что лямбда функцию из аргументов можно убрать.

2021-08-02 14:18 UTC, neudachina commented on cell/include/cell.h
> +    // total_health += (bot.militancy_ * 0.6 + bot.health_ * 0.4),
формула взялась из обсуждения того, что не только воинственность влияет на итоговую часть еды, которую забирает бот, но и здоровье
в функции split_food мы проходимся по ботам, но в таком случае только один раз, чтобы добавить к их здоровью их часть еды. а чтобы посчитать общую сумму, надо будет тогда изначально еще раз проходиться по всем. зачем это делать, если можно не делать

2021-08-02 14:24 UTC, levelup0 commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](Bot b1, Bot b2) { return b2 < b1; });
а ооо

2021-08-02 14:39 UTC, LeoProko requested changes

2021-08-02 14:39 UTC, LeoProko commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](Bot b1, Bot b2) { return b2 < b1; });
ну хз, можно для красоты убрать лямюда функцию и потому в строке 12 написать .end()

2021-08-02 14:39 UTC, LeoProko commented on cell/include/cell.h
> +    int total_health = 0;
Давай, раз эта логика относится к Cell, а не к move(...), то реализуем ее здесь.

Это можно сделать добавление функции Cell::add_bot(Bot& bot), где бот из агрумента будет пушбэкаться в дек, и потом будет выполняться логика в `total_health`.

2021-08-02 14:39 UTC, LeoProko commented on cell/include/cell.h
> +    int total_health = 0;
Раз переменная `total_health` содержит в себе не только `health`, то ее название некорректно. надо поменять

2021-08-02 14:39 UTC, LeoProko commented on cell/src/cell.cpp
> +        int tmp = b->militancy_ * 0.6 + b->health_ * 0.4;
название этой переменной ни о чем не говрит.

2021-08-03 11:49 UTC, LeoProko requested changes

2021-08-03 11:49 UTC, LeoProko commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](const Bot& b1, const Bot& b2) { return b2 < b1; });
я все еще не понимаю, зачем здесь лямюбда функция, если можно вызвать в 12 строке `.back()`?

2021-08-03 11:49 UTC, LeoProko commented on cell/src/cell.cpp
> +        Bot* father = *(++bots_.begin());
Здесь может быть утечка памяти. Что если `bots.begin() == bots.end()`?

2021-08-03 11:49 UTC, LeoProko commented on cell/src/cell.cpp
> +        Bot* father = *(++bots_.begin());
или `++bots.begin() == bots.end()`

2021-08-03 11:56 UTC, LeoProko commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](const Bot& b1, const Bot& b2) { return b2 < b1; });
или если прям надо сортить в обратном порядке, то зачем лямбда функция, если можно сделать так
```cpp
std::sort(bots_.rbegin(), bots_.rend())
```?
и все будет, как ты хочешь, -- в обратном порядке

2021-08-03 11:59 UTC, neudachina commented on cell/src/cell.cpp
> +        Bot* father = *(++bots_.begin());
там для этого есть специальная строчка `if (bots_.size() > 1)`

2021-08-03 12:00 UTC, neudachina commented on cell/src/cell.cpp
> +        std::sort(bots_.begin(), bots_.end(), [](const Bot& b1, const Bot& b2) { return b2 < b1; });
ну, я хотела выделить конкретно логику того, что мы берем первых в списке. можно и твой второй вариант использовать

2021-08-03 12:03 UTC, LeoProko requested changes

2021-08-03 12:03 UTC, LeoProko commented on cell/include/cell.h
> +    void add_bot(Bot& bot);
Давай этот метод сделаем публичным, мы же его для этих целей создали

2021-08-03 12:05 UTC, LeoProko requested changes

2021-08-03 12:05 UTC, LeoProko commented on cell/include/cell.h
> +    int total_coef_ = 0;
эта переменная вроде бы сугубо для ячейки, поэтому ее лучше сделать приватной

2021-08-03 12:13 UTC, LeoProko approved these changes

2021-08-03 13:33 UTC, levelup0 commented on run/src/run.cpp
> +        int c = 0;
мы такие переменные вроде не любим

2021-08-03 13:37 UTC, levelup0 approved these changes

2021-08-03 13:41 UTC, merged