add altruists
LeoProko/huy_simulation pull request #26
Opened 2021-08-06 18:49 UTC by LeoProko

2021-08-06 20:17 UTC, levelup0 requested changes

2021-08-06 20:17 UTC, levelup0 commented on bot/src/bot.cpp
> +    children_amount_ = std::max(0, std::min(9, static_cast<int>(children_amount_ * coefficient)));
Если все признаки от 0 до 99, а children_amount_ от 0 до 9, то калибровка работает неправильно.

2021-08-06 20:17 UTC, levelup0 commented on bot/src/bot.cpp
> +    children_amount_ = std::max(0, std::min(9, static_cast<int>(children_amount_ * coefficient)));
Можно сделать все признаки от 0 до 99, и рассчитывать реальное значение из этого.

2021-08-06 20:17 UTC, levelup0 commented on run/src/run.cpp
> +    std::cout << "Public altruists amount...." << public_altruist_amount << "\n";
неплохо 👍

2021-08-06 20:25 UTC, levelup0 requested changes

2021-08-06 20:25 UTC, levelup0 commented on bot/src/bot.cpp
> +        is_private_altruist_ *= parameters::random() % 100 > parameters::mutation;
опечатка?

2021-08-06 20:42 UTC, LeoProko commented on bot/src/bot.cpp
> +    children_amount_ = std::max(0, std::min(9, static_cast<int>(children_amount_ * coefficient)));
не совсем понимаю, как тогда будет работать `reproduce`? Как он будет понимать, сколько надо родить детей, если `children_amount` будет от 0 до 99, но для какого-то эксперимента потребуется, чтобы он был в промежутке от 0 до 9?

2021-08-06 20:45 UTC, LeoProko commented on bot/src/bot.cpp
> +    children_amount_ = std::max(0, std::min(9, static_cast<int>(children_amount_ * coefficient)));
А, типа просто делить на 10?

2021-08-07 14:23 UTC, levelup0 approved these changes

2021-08-07 14:30 UTC, merged